# Generated by Django 4.2.2 on 2023-07-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cart_quantity_shippinginformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippinginformation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
    ]
